### ISSUE TITLE
This Doesn't Seem To Work On Windows

### ISSUE THREAD

**Issue by tompurl** [rksm/clj-org-analyzer#1] opened 2019-08-13 18:32 UTC
Here's how I'm using the application on Windows:

1. I start the java program, which opens a new browser window.
2. I then tried these three paths:
  1. c:\foo\bar\org
  2. c:/foo/bar/org
  3. file:///c:/foo/bar/org (which didn't work at all)
3. Click on "confirm"

I then see the analyzer screen with 0 clocks. When I click on the "i" icon next to the clocks label I see that there are dozens of files in my org directory but none of the clock entries are found.

What can I do to help debug this issue? Is it possible to turn up logging for example?

**Comment by hso** [comment] 2019-08-13 19:11
I'm having this same issue on Windows. Clicking on the "i" icon shows my org files, but no clock entries are shown.

**Comment by rksm** [comment] 2019-08-13 22:35
Just tested it on Windows and it seems to work fine. This might be a different issue that you ran into (whitespace in front of clocks) and that was just fixed. Could you please test [version 0.3.0](https://github.com/rksm/clj-org-analyzer/releases/latest) and see if the issue is fixed. Thank you!

**Comment by hso** [comment] 2019-08-13 23:07
There might be a different issue here. I just tested version 0.3.0 and
still nothing shows up on the browser.

**Comment by rksm** [comment] 2019-08-14 15:02
OK, thanks for trying it. I need to reproduce it somehow. Can you let me know what version of Java you're running? (`java -version`). Could you make an org file that doesn't work available? Can be made up content, just a bit of the structure needs to match.

**Comment by hso** [comment] 2019-08-14 15:16
Of course, and if I could help you reproduce it and debug it, can you write some build instructions?

Java version:
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

[hello.zip](https://github.com/rksm/clj-org-analyzer/files/3502035/hello.zip)

**Comment by hso** [comment] 2019-08-14 21:22
I know what it is. My locale is es_CL.UTF-8 and org-mode writes my timestamps like this: `[2019-08-13 mar. 14:59]`. As soon as I changed (manually) the day name to english (i.e. `Tue`) it showed up on the calendar.

A small fix to your regexps for timestamp parsing will do.

Thank you!

**Comment by rksm** [comment] 2019-08-15 03:26
Awesome, thanks for letting me know, will be fixed tomorrow.

**Comment by hso** [comment] 2019-08-15 03:58
I already fixed it in the pull request ;)

**Closed as completed** 2019-08-15 21:14 UTC

**Comment by tompurl** [comment] 2019-08-16 19:17
> Just tested it on Windows and it seems to work fine. This might be a different issue that you ran into (whitespace in front of clocks) and that was just fixed. Could you please test [version 0.3.0](https://github.com/rksm/clj-org-analyzer/releases/latest) and see if the issue is fixed. Thank you!

Needless to say this worked for me. Thank you for fixing it so quickly and for providing this excellent software.
